apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-storageclass-premium
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  storageaccounttype: Premium_LRS
  kind: managed