apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
  labels:
    app: sampleapp
spec:
  type: LoadBalancer
  selector:
    app: sampleapp
  ports:
    - port: 80
      targetPort: 80