apiVersion: v1
kind: Service
metadata:
  name: acrimage-service
  labels:
    app: acr-image
spec:
  type: LoadBalancer
  selector:
    app: acr-image
  ports:
    - port: 80
      targetPort: 80