apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretdeployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: secret
  template: 
    metadata: 
      labels: 
        app: secret
    spec: 
      containers:
      - name: secretdeployment
        image: nginx
        volumeMounts:
        - name: secretvolume
          mountPath: /etc/name
      volumes:
      - name: secretvolume
        secret:
          secretName: credentials