apiVersion: v1
kind: Service
metadata:
  name: azure-file-service
  labels: 
    app: azure-files
spec:
  type: LoadBalancer
  selector:
    app: azure-files
  ports: 
    - port: 80
      targetPort: 80