apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-storageclass-standardlrs-file
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true 
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
parameters:
  skuName: Standard_LRS