apiVersion: v1 
kind: Service 
metadata:
  name: redis
  labels:
    name: redis-service
    tier: middle
spec:
  selector:
    name: redisapp
    tier: middle
  ports:
    - port: 6379
      targetPort: 6379