apiVersion: v1 
kind: Service 
metadata:
  name: result-app-service
spec:
  type: LoadBalancer
  selector:
    name: resultapp
    tier: front-end
  ports:
    - port: 80
      targetPort: 80