apiVersion: v1
kind: Service
metadata:
  name: welcome-pod-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80 #Service
      targetPort: 80 #Container Port