apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels:
    app: backend-application
    tier: backend   
spec:
  type: ClusterIP
  selector:
    app: backend-application
  ports:
    - name: http
      port: 8080
      targetPort: 8080