apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-pod-autoscaler-hpa
spec:
  maxReplicas: 20
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: horizontal-pod-autoscaler-deployment
  targetCPUUtilizationPercentage: 25