apiVersion: v1
kind: Service
metadata:
  name: horizontal-pod-autoscaler-service
  labels:
    app: horizontal-pod-autoscaler
spec:
  type: LoadBalancer
  selector:
    app: horizontal-pod-autoscaler
  ports:
    - port: 80
      targetPort: 80